import {StyleSheet} from "react-native";
const colors = require("../../color/Colors").default;
import {Platform} from "react-native"

export default (styles = StyleSheet.create({
  fullViewVerticalCenter: {
    flex: 1,
    width: '100%',
    height: '100%',
    alignContent: 'center',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.8,
  },
  fullViewVerticalTopDown: {
    flex: 1,
    width: '100%',
    height: '100%',
    // alignContent: "center",
    // flexDirection: "column",
    alignItems: 'center',
    // justifyContent: "center",
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.8,
  },
  fullViewVerticalBottomUp: {
    flex: 1,
    width: '100%',
    height: '100%',
    // alignContent: "center",
    // flexDirection: "column",
    alignItems: 'center',
    // justifyContent: "center",
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.8,
    flexDirection: 'column-reverse',
  },
  fullViewCenterHorizontal: {
    flex: 1,
    alignContent: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  toolBar: {
    backgroundColor: 'red',
    width: '100%',
    height: 45,
    alignItems: 'center',
    justifyContent: 'space-between',
    flexDirection: 'row',
    // position: "absolute",
    top: 0,
    backgroundColor: colors.theme,
    alignItems: 'center',
  },
  gradientToolBar: {
      height: 45, 
      flex: 1,
      alignItems: "flex-end",
      justifyContent: "center",
    },
  text: {
    color: '#ffffff',
    fontFamily: 'Arial',
  },
  textBold: {
    fontWeight: 'bold',
  },
  screenWithToolBar: {
    flexDirection: 'column',
    justifyContent: 'flex-start',
  },
  toolBarBtn: {
    width: 100,
    height: 35,
    backgroundColor: colors.toolBarBtn,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 25,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    padding: 10,
  },
  toolBarBtnHome: {
    width: 40,
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  toolBarTitle: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 17,
  },
  divForm: {
    backgroundColor: '#fff',
    width: 320,
    marginTop: 50,
    height: 400,
    // flex: 1
    shadowColor: '#000',
    shadowOffset: {width: 10, height: 10},
    elevation: 10,
    justifyContent: 'flex-start',
    alignItems: 'center',
    flexDirection: 'column',
  },
  divFormTitle: {
    fontWeight: '200',
    fontSize: 16,
    color: '#fff',
    top: 0,
    backgroundColor: colors.theme2,
    width: '100%',
    height: 25,
    textAlign: 'center',
    textAlignVertical: "center",
    paddingTop: Platform.OS == "ios" ? 2 : 0,
    fontWeight: "bold"
  },
  dateTimePicker: {
    position: 'absolute',
    alignSelf: 'center',
    width: 300,
    height: 300,
    bottom: 80,
    backgroundColor: "#fff",
    shadowColor: "#000",
    shadowOffset: {width: 1, height: 2},
    elevation: 10,
    shadowOpacity: 0.3,
    bottom: 0
  },
  alert: {
    position: 'absolute',
    alignSelf: 'center',
  },
}));